# config.yaml - MINIMAL CHANGES to enable LSTM predictions

# FRENZ Device Configuration
frenz_device:
  device_id: "FRENZJ12"
  product_key: "YOUR_PRODUCT_KEY" # Store securely

# Data Paths
paths:
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"
  model_save_dir: "models/saved_models/"
  log_dir: "logs/"
  ui_assets: "ui_assets/"
  binaural_sounds_dir: "ui_assets/sounds/binaural/"

# Session Metadata
session_info:
  conditions: ["Induction", "Sham"]

# Signal Processing Parameters
signal_processing:
  eeg:
    sample_rate: 125       # Hz
    total_channels_from_device: 6 # Total channels FRENZ provides
    active_channels_indices: [0, 1, 3, 4] # Indices for LF, RF from the 6 channels
    active_channels_names: ['LF', 'RF', 'OTEL', 'OTER'] # Names of active channels
    
    # Preprocessing
    theta_bandpass_lowcut: 4.0  # Hz 
    theta_bandpass_highcut: 8.0 # Hz
    notch_freq: 60.0            # Hz
    # Amplitude artifact rejection threshold in microvolts
    artifact_amplitude_threshold_uv: 600000.0 # microVolts
    # Signal Quality Check
    sqc_good_threshold: 0  
    sqc_fs_divisor: 375
    # Scaling factor to convert raw EEG units to microVolts. If raw is already uV, this is 1.0.
    eeg_uv_scaling_factor: 1.0

    # Override hardcoded channel thresholds
    channel_sqc_thresholds:
      LF: 0      
      OTEL: 0    
      RF: 0     
      OTER: 0    

    # Feature extraction windowing
    feature_window_sec: 4      # Seconds for feature calculation window
    feature_overlap_ratio: 0.5   # 50% overlap (for 2-second step)
    
    # PSD and Feature specific
    psd_nperseg_sec: 4         # Seconds for PSD window 
    theta_band_actual: [4.0, 8.0] # Hz 
    alpha_band: [8.0, 13.0]
    # Reference band for relative power and SEF calculations
    total_power_reference_band: [1.0, 30.0] # Hz 
    sef_percentage: 0.95       # For SEF95 

    # ML-compatible epoch quality assessment parameters
    epoch_artifact_threshold_pct: 50.0  
    enable_session_level_epoch_gating: false  
    
    # Debug mode for detailed rejection analysis
    debug_epoch_rejection: true 

  # PPG Configuration
  ppg:
    sample_rate: 25
    lowpass_cutoff_hz: 3.0
    hrv_window_sec: 4
    feature_overlap_ratio: 0.5
    min_peak_distance_sec: 0.35
    min_beat_interval_sec: 0.33  
    max_beat_interval_sec: 2.0   
    ibi_ectopic_threshold_ratio: 0.25  
    ppg_filter_order: 3  

  # IMU Configuration: # Kept for Stillness score
  imu:
    sample_rate: 50
    movement_analysis_window_sec: 4
    feature_overlap_ratio: 0.5
    stillness_threshold: 0.02
    accel_gravity_value: 9.80665
    stillness_epsilon: 1e-9  
    lowpass_cutoff_hz: 5.0   
    filter_order: 4         

# Model Parameters (LSTM input will be a combination of EEG, PPG, IMU features)
model:
  lstm:
    sequence_length: 15 # Number of 4s windows (e.g., 15 windows * 2s step = 30s sequences)
    batch_size: 32
    epochs: 100
    learning_rate: 0.001

# Real-time System
real_time:
  # How often the system processes a new 4s window (due to 2s overlap/step)
  processing_interval_sec: 2 # Corresponds to step time of EEG window
  buffer_size_sec: 20 # seconds of raw data to keep for processing pipeline

# Visualization
visualization:
  refresh_rate_ms: 500 # Update meditation score graph every 0.5s

# Binaural Beats
binaural_beats:
  default_frequency: 7.0
  volume: 0.5